#!/bin/sh

# 0-512
absolute_brightness=$(brightnessctl g)

brightness_percentage=$( awk "BEGIN {print ($absolute_brightness/512)*100}" | cut -f1 -d. )

printf "^c#d79921^^d^ %s%%" "$brightness_percentage"
