#!/bin/sh

case $BLOCK_BUTTON in
    1) echo "hi" && pulsemixer --mute ;;
    2) pulsemixer --mute ;;
    3) pulsemixer --mute ;;
esac

date=$(date "+%b %d/%m/1984 %a")
printf "^c#d83a27^ ^d^ %s" "$date"
