#!/bin/sh

uptime_seconds=$(awk {'print $1'} /proc/uptime | cut -d. -f1)

if [ $uptime_seconds -lt 3600 ]; then
    uptime=$(date -d@$uptime_seconds -u "+%-M min")
else
    uptime=$(date -d@$uptime_seconds -u "+%-Hh %-Mmin")
fi

printf "^c#d65d0e^ ^d^ %s" "$uptime"
