#!/bin/sh


[ $(pulsemixer --get-mute) -eq "1" ] && echo " ^c#fb4934^婢^d^ " && exit

vol="$(pulsemixer --get-volume | awk '{print $1}')"

if [ "$vol" -gt "100" ]; then
	icon=""
elif [ "$vol" -ge "60" ]; then
	icon="墳"
elif [ "$vol" -gt "30" ]; then
	icon="奔"
elif [ "$vol" -gt "0" ]; then
	icon="奄"
else 
    icon="ﱝ" 
fi

echo "^c#689d6a^$icon^d^ $vol%"
